### ISSUE TITLE
Connect with jsx

### ISSUE THREAD

**Issue by c0nsoleg** [mvanroon/react-native-axios-jwt#14]
Any success in using it with libraries like react-navigation and make use of isLoggedIn to conditional render something?

**Comment by mvanroon** [comment]
I don’t see how this library has anything to do with react navigation or conditional rendering.

**Comment by ericlifs** [comment]
Thanks for this awesome tool! I'm facing the same issue @c0nsoleg tho: there is no way to react to when the user gets logged in or logged out in order to do something like:

```
if (userIsLoggedIn()) {
  return <HomeNavigation />;
}

return <AuthNavigation />;
```

You can answer with "this library is just for setting the axios headers interceptors" and you would be 100% right, but at the same time would be nice to have the possibility to respond accordingly.

Thanks!

**Comment by mvanroon** [comment]
Hi @ericlifs, have you tried using the `isLoggedIn` function that is exported from this library?

**Comment by ericlifs** [comment]
Hey @mvanroon, how are you? Yes, I've tried using that `isLoggedIn` function but it doesn't fit our requirement as it is an async function that returns a boolean indicating whether the user is logged at the time of calling the function or not. We were talking about having a function/hook that returns a boolean indicating when the headers are set or not, by doing that you can react to changes on this boolean and show different navigators if the user is logged in or not.

Also, there is a "bug" in the readme file: this is the code for the `isLoggedIn` function:

```
/**
 * Checks if refresh tokens are stored
 * @async
 * @returns {Promise<boolean>} Whether the user is logged in or not
 */
export const isLoggedIn = async (): Promise<boolean> => {
  const token = await getRefreshToken()
  return !!token
}
```

If you do in your code:

```
if (isLoggedIn()) {
  console.log('logged in')
} else {
  console.log('not logged in')
}
```

It will always show 'logged in' because the `isLoggedIn` function is an async function and therefore returns a Promise<boolean> which is always true (you'll always need to await that call).

Eric.

**Comment by mvanroon** [comment]
You’re right! Looks like the readme needs to be updated. Could you open a PR?

As for ‘caching’ the auth state. You could build this in your own project or we could create a hook that returns the logged in state. This state would need to be updated when a user logs in or out.
